name: dbt_anywhere
version: "1.0.0"
profile: dbt_anywhere

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_anywhere:
    staging:
      +materialized: view
    marts:
      +materialized: table
